# Generated by Django 3.2.7 on 2021-09-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_auto_20210923_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, null=True)),
                ('prenom', models.CharField(max_length=300, null=True)),
                ('telephone', models.CharField(max_length=300, null=True)),
                ('localisation', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Commande.client'),
        ),
    ]
