# Generated by Django 3.2.7 on 2021-09-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0002_atelier'),
        ('Commande', '0003_auto_20210923_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artisan_app.artisan'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
