# Generated by Django 3.2.7 on 2021-09-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0004_auto_20210923_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
    ]
