# Generated by Django 3.2.7 on 2021-09-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0002_atelier'),
        ('Commande', '0005_remove_commande_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artisan_app.artisan'),
        ),
    ]
