# Generated by Django 3.2.7 on 2021-09-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0002_atelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/image_atelier'),
        ),
    ]
