# Generated by Django 3.2.7 on 2021-09-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0003_atelier_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atelier',
            old_name='descrption',
            new_name='description',
        ),
    ]
